<?php
/**
 * InternationalOrderInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Dana\Widget
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Widget API
 *
 * API for enabling the user to make payment from merchant's platform with redirecting to DANA's platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dana\Widget\v1\Model;

use \ArrayAccess;
use \Dana\ObjectSerializer;
use \Dana\Model\ModelInterface;

/**
 * InternationalOrderInfo Class Doc Comment
 *
 * @category Class
 * @description Additional information for international orders (non-IDR currency transactions)
 * @package  Dana\Widget
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InternationalOrderInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InternationalOrderInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'originOrderAmount' => '\Dana\Widget\v1\Model\Money',
        'exchangeRate' => '\Dana\Widget\v1\Model\InternationalOrderInfoExchangeRate',
        'totalAmount' => '\Dana\Widget\v1\Model\Money',
        'paymentPromoInfo' => '\Dana\Widget\v1\Model\PaymentPromoInfo',
        'refundPromoInfo' => '\Dana\Widget\v1\Model\RefundPromoInfo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'originOrderAmount' => null,
        'exchangeRate' => null,
        'totalAmount' => null,
        'paymentPromoInfo' => null,
        'refundPromoInfo' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'originOrderAmount' => false,
        'exchangeRate' => false,
        'totalAmount' => false,
        'paymentPromoInfo' => false,
        'refundPromoInfo' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'originOrderAmount' => 'originOrderAmount',
        'exchangeRate' => 'exchangeRate',
        'totalAmount' => 'totalAmount',
        'paymentPromoInfo' => 'paymentPromoInfo',
        'refundPromoInfo' => 'refundPromoInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'originOrderAmount' => 'setOriginOrderAmount',
        'exchangeRate' => 'setExchangeRate',
        'totalAmount' => 'setTotalAmount',
        'paymentPromoInfo' => 'setPaymentPromoInfo',
        'refundPromoInfo' => 'setRefundPromoInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'originOrderAmount' => 'getOriginOrderAmount',
        'exchangeRate' => 'getExchangeRate',
        'totalAmount' => 'getTotalAmount',
        'paymentPromoInfo' => 'getPaymentPromoInfo',
        'refundPromoInfo' => 'getRefundPromoInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('originOrderAmount', $data ?? [], null);
        $this->setIfExists('exchangeRate', $data ?? [], null);
        $this->setIfExists('totalAmount', $data ?? [], null);
        $this->setIfExists('paymentPromoInfo', $data ?? [], null);
        $this->setIfExists('refundPromoInfo', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets originOrderAmount
     *
     * @return \Dana\Widget\v1\Model\Money|null
     */
    public function getOriginOrderAmount()
    {
        return $this->container['originOrderAmount'];
    }

    /**
     * Sets originOrderAmount
     *
     * @param \Dana\Widget\v1\Model\Money|null $originOrderAmount Origin order amount in the original currency. Contains value (amount including cents) and currency (code based on ISO)
     *
     * @return self
     */
    public function setOriginOrderAmount($originOrderAmount)
    {
        if (is_null($originOrderAmount)) {
            throw new \InvalidArgumentException('non-nullable originOrderAmount cannot be null');
        }
        $this->container['originOrderAmount'] = $originOrderAmount;

        return $this;
    }

    /**
     * Gets exchangeRate
     *
     * @return \Dana\Widget\v1\Model\InternationalOrderInfoExchangeRate|null
     */
    public function getExchangeRate()
    {
        return $this->container['exchangeRate'];
    }

    /**
     * Sets exchangeRate
     *
     * @param \Dana\Widget\v1\Model\InternationalOrderInfoExchangeRate|null $exchangeRate exchangeRate
     *
     * @return self
     */
    public function setExchangeRate($exchangeRate)
    {
        if (is_null($exchangeRate)) {
            throw new \InvalidArgumentException('non-nullable exchangeRate cannot be null');
        }
        $this->container['exchangeRate'] = $exchangeRate;

        return $this;
    }

    /**
     * Gets totalAmount
     *
     * @return \Dana\Widget\v1\Model\Money|null
     */
    public function getTotalAmount()
    {
        return $this->container['totalAmount'];
    }

    /**
     * Sets totalAmount
     *
     * @param \Dana\Widget\v1\Model\Money|null $totalAmount Total amount after conversion. Contains value (amount including cents) and currency (code based on ISO)
     *
     * @return self
     */
    public function setTotalAmount($totalAmount)
    {
        if (is_null($totalAmount)) {
            throw new \InvalidArgumentException('non-nullable totalAmount cannot be null');
        }
        $this->container['totalAmount'] = $totalAmount;

        return $this;
    }

    /**
     * Gets paymentPromoInfo
     *
     * @return \Dana\Widget\v1\Model\PaymentPromoInfo|null
     */
    public function getPaymentPromoInfo()
    {
        return $this->container['paymentPromoInfo'];
    }

    /**
     * Sets paymentPromoInfo
     *
     * @param \Dana\Widget\v1\Model\PaymentPromoInfo|null $paymentPromoInfo Define the detail of payment promo information, contains promotion that handled and set by merchant
     *
     * @return self
     */
    public function setPaymentPromoInfo($paymentPromoInfo)
    {
        if (is_null($paymentPromoInfo)) {
            throw new \InvalidArgumentException('non-nullable paymentPromoInfo cannot be null');
        }
        $this->container['paymentPromoInfo'] = $paymentPromoInfo;

        return $this;
    }

    /**
     * Gets refundPromoInfo
     *
     * @return \Dana\Widget\v1\Model\RefundPromoInfo|null
     */
    public function getRefundPromoInfo()
    {
        return $this->container['refundPromoInfo'];
    }

    /**
     * Sets refundPromoInfo
     *
     * @param \Dana\Widget\v1\Model\RefundPromoInfo|null $refundPromoInfo Define the detail of refund promo information
     *
     * @return self
     */
    public function setRefundPromoInfo($refundPromoInfo)
    {
        if (is_null($refundPromoInfo)) {
            throw new \InvalidArgumentException('non-nullable refundPromoInfo cannot be null');
        }
        $this->container['refundPromoInfo'] = $refundPromoInfo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


