<?php
/**
 * AmountDetail
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Dana\PaymentGateway
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway API
 *
 * API for doing operations in DANA Payment Gateway (Gapura)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dana\PaymentGateway\v1\Model;

use \ArrayAccess;
use \Dana\ObjectSerializer;
use \Dana\Model\ModelInterface;

/**
 * AmountDetail Class Doc Comment
 *
 * @category Class
 * @package  Dana\PaymentGateway
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AmountDetail implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AmountDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'orderAmount' => '\Dana\PaymentGateway\v1\Model\Money',
        'payAmount' => '\Dana\PaymentGateway\v1\Model\Money',
        'voidAmount' => '\Dana\PaymentGateway\v1\Model\Money',
        'confirmAmount' => '\Dana\PaymentGateway\v1\Model\Money',
        'refundAmount' => '\Dana\PaymentGateway\v1\Model\Money',
        'chargebackAmount' => '\Dana\PaymentGateway\v1\Model\Money',
        'chargeAmount' => '\Dana\PaymentGateway\v1\Model\Money'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'orderAmount' => null,
        'payAmount' => null,
        'voidAmount' => null,
        'confirmAmount' => null,
        'refundAmount' => null,
        'chargebackAmount' => null,
        'chargeAmount' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'orderAmount' => false,
        'payAmount' => false,
        'voidAmount' => false,
        'confirmAmount' => false,
        'refundAmount' => false,
        'chargebackAmount' => false,
        'chargeAmount' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'orderAmount' => 'orderAmount',
        'payAmount' => 'payAmount',
        'voidAmount' => 'voidAmount',
        'confirmAmount' => 'confirmAmount',
        'refundAmount' => 'refundAmount',
        'chargebackAmount' => 'chargebackAmount',
        'chargeAmount' => 'chargeAmount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'orderAmount' => 'setOrderAmount',
        'payAmount' => 'setPayAmount',
        'voidAmount' => 'setVoidAmount',
        'confirmAmount' => 'setConfirmAmount',
        'refundAmount' => 'setRefundAmount',
        'chargebackAmount' => 'setChargebackAmount',
        'chargeAmount' => 'setChargeAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'orderAmount' => 'getOrderAmount',
        'payAmount' => 'getPayAmount',
        'voidAmount' => 'getVoidAmount',
        'confirmAmount' => 'getConfirmAmount',
        'refundAmount' => 'getRefundAmount',
        'chargebackAmount' => 'getChargebackAmount',
        'chargeAmount' => 'getChargeAmount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('orderAmount', $data ?? [], null);
        $this->setIfExists('payAmount', $data ?? [], null);
        $this->setIfExists('voidAmount', $data ?? [], null);
        $this->setIfExists('confirmAmount', $data ?? [], null);
        $this->setIfExists('refundAmount', $data ?? [], null);
        $this->setIfExists('chargebackAmount', $data ?? [], null);
        $this->setIfExists('chargeAmount', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['orderAmount'] === null) {
            $invalidProperties[] = "'orderAmount' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets orderAmount
     *
     * @return \Dana\PaymentGateway\v1\Model\Money
     */
    public function getOrderAmount()
    {
        return $this->container['orderAmount'];
    }

    /**
     * Sets orderAmount
     *
     * @param \Dana\PaymentGateway\v1\Model\Money $orderAmount Order amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br>
     *
     * @return self
     */
    public function setOrderAmount($orderAmount)
    {
        if (is_null($orderAmount)) {
            throw new \InvalidArgumentException('non-nullable orderAmount cannot be null');
        }
        $this->container['orderAmount'] = $orderAmount;

        return $this;
    }

    /**
     * Gets payAmount
     *
     * @return \Dana\PaymentGateway\v1\Model\Money|null
     */
    public function getPayAmount()
    {
        return $this->container['payAmount'];
    }

    /**
     * Sets payAmount
     *
     * @param \Dana\PaymentGateway\v1\Model\Money|null $payAmount Pay amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br>
     *
     * @return self
     */
    public function setPayAmount($payAmount)
    {
        if (is_null($payAmount)) {
            throw new \InvalidArgumentException('non-nullable payAmount cannot be null');
        }
        $this->container['payAmount'] = $payAmount;

        return $this;
    }

    /**
     * Gets voidAmount
     *
     * @return \Dana\PaymentGateway\v1\Model\Money|null
     */
    public function getVoidAmount()
    {
        return $this->container['voidAmount'];
    }

    /**
     * Sets voidAmount
     *
     * @param \Dana\PaymentGateway\v1\Model\Money|null $voidAmount Void amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br>
     *
     * @return self
     */
    public function setVoidAmount($voidAmount)
    {
        if (is_null($voidAmount)) {
            throw new \InvalidArgumentException('non-nullable voidAmount cannot be null');
        }
        $this->container['voidAmount'] = $voidAmount;

        return $this;
    }

    /**
     * Gets confirmAmount
     *
     * @return \Dana\PaymentGateway\v1\Model\Money|null
     */
    public function getConfirmAmount()
    {
        return $this->container['confirmAmount'];
    }

    /**
     * Sets confirmAmount
     *
     * @param \Dana\PaymentGateway\v1\Model\Money|null $confirmAmount Confirm amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br>
     *
     * @return self
     */
    public function setConfirmAmount($confirmAmount)
    {
        if (is_null($confirmAmount)) {
            throw new \InvalidArgumentException('non-nullable confirmAmount cannot be null');
        }
        $this->container['confirmAmount'] = $confirmAmount;

        return $this;
    }

    /**
     * Gets refundAmount
     *
     * @return \Dana\PaymentGateway\v1\Model\Money|null
     */
    public function getRefundAmount()
    {
        return $this->container['refundAmount'];
    }

    /**
     * Sets refundAmount
     *
     * @param \Dana\PaymentGateway\v1\Model\Money|null $refundAmount Refund amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br>
     *
     * @return self
     */
    public function setRefundAmount($refundAmount)
    {
        if (is_null($refundAmount)) {
            throw new \InvalidArgumentException('non-nullable refundAmount cannot be null');
        }
        $this->container['refundAmount'] = $refundAmount;

        return $this;
    }

    /**
     * Gets chargebackAmount
     *
     * @return \Dana\PaymentGateway\v1\Model\Money|null
     */
    public function getChargebackAmount()
    {
        return $this->container['chargebackAmount'];
    }

    /**
     * Sets chargebackAmount
     *
     * @param \Dana\PaymentGateway\v1\Model\Money|null $chargebackAmount Chargeback amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br>
     *
     * @return self
     */
    public function setChargebackAmount($chargebackAmount)
    {
        if (is_null($chargebackAmount)) {
            throw new \InvalidArgumentException('non-nullable chargebackAmount cannot be null');
        }
        $this->container['chargebackAmount'] = $chargebackAmount;

        return $this;
    }

    /**
     * Gets chargeAmount
     *
     * @return \Dana\PaymentGateway\v1\Model\Money|null
     */
    public function getChargeAmount()
    {
        return $this->container['chargeAmount'];
    }

    /**
     * Sets chargeAmount
     *
     * @param \Dana\PaymentGateway\v1\Model\Money|null $chargeAmount Charge amount. Contains two sub-fields:<br> 1. Value: Transaction amount, including the cents<br> 2. Currency: Currency code based on ISO<br>
     *
     * @return self
     */
    public function setChargeAmount($chargeAmount)
    {
        if (is_null($chargeAmount)) {
            throw new \InvalidArgumentException('non-nullable chargeAmount cannot be null');
        }
        $this->container['chargeAmount'] = $chargeAmount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


